version: '2'

services:

    ng2-templates:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./dist:/usr/share/nginx/html

        ports:
            - "3474:80"
